### ISSUE TITLE
[TODO] Refactoring Project

### ISSUE THREAD

**Issue by joaoarmando** [joaoarmando/coursei#1]
### **Business Logic**
- [x] Remove duplicated code in getCourses and getNextCourses
- [x] Move getCourses and getNextCourses to  CoursesRepository.
- [x] Move saveCourse from CoursesRepository to UserRepository.
- [x] Move removeSavedCourse from CoursesRepository to UserRepository.
- [x] Move getSavedCoursesCountFromServer from CoursesRepository to UserRepository.
- [x] Move clearNotificationBadge from CoursesRepository to UserRepository.
- [ ] Fix a bug that prevent ParseServer to return data after [Upgrading pre 1.12 Android project](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects)
### **Widgets**
- [x] Remove all "prefix0" from widgets
- [ ] Remove unnecessary FutureBuiders
